# Generated by Django 6.0.4 on 2026-05-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
    ]
